### ISSUE TITLE
Cannot read property 'onDidChangeStatuses' of undefined

### ISSUE THREAD

**Issue by apopa116** [atom/status-bar#158] opened 2016-07-16 13:02 UTC
When opening Atom.

**Atom Version**: 1.8.0
**System**: Linux Mint
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package, v1.4.0

### Stack Trace

Failed to activate the status-bar package

```
At Cannot read property 'onDidChangeStatuses' of undefined

TypeError: Cannot read property 'onDidChangeStatuses' of undefined
    at GitRepository.module.exports.GitRepository.onDidChangeStatuses (/usr/share/atom/resources/app.asar/src/git-repository.js:131:24)
    at status-bar-git.GitView.subscribeToRepositories (/usr/share/atom/resources/app.asar/node_modules/status-bar/lib/git-view.js:106:61)
    at status-bar-git.GitView.initialize (/usr/share/atom/resources/app.asar/node_modules/status-bar/lib/git-view.js:32:12)
    at Object.module.exports.activate (/usr/share/atom/resources/app.asar/node_modules/status-bar/lib/main.js:67:16)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:497:46)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:754:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tool-bar-almighty",
      "tool-bar",
      "synced-sidebar",
      "split-diff",
      "atom-beautify",
      "atom-formatter-jsbeautify",
      "autocomplete-modules",
      "autocomplete-paths",
      "define-jump",
      "emmet",
      "es6-javascript",
      "file-type-icons",
      "formatter",
      "git-control",
      "git-plus",
      "git-projects",
      "highlight-line",
      "highlight-selected",
      "javascript-snippets",
      "linter",
      "linter-eslint",
      "minimap",
      "minimap-highlight-selected",
      "neon-cursor",
      "pigments",
      "react",
      "react-snippets",
      "set-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by apopa116** [comment] 2016-07-16 17:11
I've checked and app.asar isn't a directory, but a file.

**Comment by ad222kr** [comment] 2016-07-16 17:24
I get the same error on a freshly installed Atom on Ubuntu 16.04. No community packages installed.
This only happens when I try to open a folder that is a git-repository.

**Comment by lee-dohm** [comment] 2016-07-16 17:35
This is a duplicate of #157. You may want to subscribe there for updates.

**Closed by lee-dohm** 2016-07-16 17:35 UTC
