### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isVisible' of null

### ISSUE THREAD

**Issue by udayms** [atom/status-bar#199] opened 2017-06-30 18:37 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package 1.8.11

### Stack Trace

Uncaught TypeError: Cannot read property 'isVisible' of null

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/status-bar/lib/main.js:51

TypeError: Cannot read property 'isVisible' of null
    at atom-workspace.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/status-bar/lib/main.js:51:41)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:106:35)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:313:26)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:81:20)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -1:04.7.0 core:paste (input.hidden-input)
     -1:04.1.0 core:undo (input.hidden-input)
     -1:02.9.0 core:paste (input.hidden-input)
     -1:00.1.0 intentions:highlight (input.hidden-input)
  5x -0:59.9.0 editor:move-to-beginning-of-word (input.hidden-input)
  4x -0:57.5.0 core:move-left (input.hidden-input)
     -0:54.3.0 core:save (input.hidden-input)
     -0:51.2.0 editor:newline (input.hidden-input)
  3x -0:47.7.0 core:backspace (input.hidden-input)
     -0:44.7.0 autocomplete-plus:confirm (input.hidden-input)
     -0:44.7.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -0:42.5.0 autocomplete-plus:confirm (input.hidden-input)
  2x -0:41.7.0 core:save (input.hidden-input)
     -0:09.3.0 command-palette:toggle (input.hidden-input)
     -0:05.7.0 core:confirm (input.hidden-input)
     -0:05.7.0 status-bar:toggle (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
atom-beautify 0.30.3 
atom-desert-syntax 0.3.0 
atom-less 0.1.10 
atom-storm-ui 2.0.1 
atom-typescript 11.0.4 
autoclose-html 0.23.0 
busy-signal 1.4.3 
compare-files 0.8.0 
context-git 0.16.2 
emmet 2.4.3 
filesize 3.0.0 
flex-tool-bar 0.12.0 
fold-functions 0.5.0 
formatter-jsbeautify 1.0.2 
git-control 0.9.0 
git-time-machine 1.5.9 
github-atom-light-syntax 0.5.0 
gl-light-syntax 3.0.0 
goto-definition 1.3.3 
highlight-selected 0.13.1 
intentions 1.1.2 
json-generator 0.1.15 
kuali-dark-ui 1.0.0 
language-json-comments 0.16.3 
linter 2.2.0 
linter-csslint 1.3.4 
linter-htmlhint 1.3.3 
linter-jshint 3.1.4 
linter-jsonlint 1.3.0 
linter-ui-default 1.6.2 
local-history 4.3.0 
material-design-syntax 1.8.0 
merge-conflicts 1.4.5 
minimap 4.28.2 
native-ui 0.21.0 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
pigments 0.39.1 
pretty-json 1.6.3 
project-manager 3.3.5 
project-viewer 1.2.0 
remember-folds 0.3.0 
remote-sync 4.1.5 
set-syntax 0.3.2 
seti-icons 1.5.4 
spacegray-light-neue-ui 0.1.7 
sync-settings 0.8.2 
todo-show 1.11.0 
tool-bar 1.1.0 
tool-bar-almighty 0.8.2 
tree-view-git-status 1.4.0 
```

**Comment by rsese** [comment] 2017-06-30 20:37
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by rsese** [comment] 2017-12-21 19:39
Thanks again for your issue!

Came across this one while looking at https://github.com/atom/atom/issues/16419 - we haven't received a response to our question in this comment https://github.com/atom/status-bar/issues/199#issuecomment-312367399. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by rsese** 2017-12-21 19:39 UTC
Labels: more-information-needed, uncaught-exception

**Comment by IsidoroMartin** [comment] 2019-10-09 15:38
Hello @rsese ,
I am having the same error.
I just installed atom and the plugin tree-view-finder and it doesn't work.
I tried restarting atom and i get the same error:
```
At ........\.atom\packages\tree-view-finder\lib\tree-view-finder.coffee:105

TypeError: Cannot read property 'isVisible' of null
    at Object.toggle (/packages/tree-view-finder/lib/tree-view-finder.coffee:105:29)
    at /packages/tree-view-finder/lib/tree-view-finder.coffee:57:91)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:349123)
    at KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1249835)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1245969)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:284329)
```

### Commands

```
  2x -1:11.8.0 tree-view-finder:toggle (atom-pane.pane.active)
```

### Non-Core Packages

```
tree-view-finder 0.2.1 
```
I am running it on Windows 10.
Best Regards

**Comment by rsese** [comment] 2019-10-09 17:23
@IsidoroMartin that looks like an [issue with tree-view-finder](https://github.com/hanyazou/tree-view-finder/issues?utf8=%E2%9C%93&q=is%3Aissue+Uncaught+TypeError%3A+Cannot+read+property+%27isVisible%27+of+null+) rather than Atom.  The package doesn't look like it's been updated in a while so that may be part of the problem.

**Comment by IsidoroMartin** [comment] 2019-10-11 14:33
@rsese You're right. I alredy post the issue on their github. Anyways i alredy found another plugin that makes what's needed so i'll use it meanwhile.
Thanks for the reply
Best Regards
