### ISSUE TITLE
I can't see my active Git branch, I don't know why

### ISSUE THREAD

**Issue by maldad** [atom/status-bar#105] opened 2015-10-10 08:08 UTC
I can see file path, cursor position and grammar, but not branch, even commits doesn't appear, and I'm working on a git directory :/
![image](https://cloud.githubusercontent.com/assets/11675538/10410076/1f623bfa-6efc-11e5-9c0d-174b3d1f4902.png)

![image](https://cloud.githubusercontent.com/assets/11675538/10410078/2e0176f8-6efc-11e5-873e-c09354d77c1d.png)

**Comment by thomasjo** [comment] 2015-10-10 09:33
Are you able to reproduce this in safe mode? `atom --safe`
In addition, which version of Atom are you using and what OS?

**Comment by maldad** [comment] 2015-10-11 07:52
Thanks for the attention, yes i can do ``` atom --safe ```
![image](https://cloud.githubusercontent.com/assets/11675538/10415876/b7a4850a-6fc2-11e5-9108-eaac441d7028.png)

And i'm using 
##### Atom 1.0.19, 
downloaded from the web page, (a .deb file)
##### OS: Elementary OS 0.3.1 Freya 64 bits

**Comment by simonvanderveldt** [comment] 2016-02-22 13:53
This seems to be the case when the root directory you've opened isn't a git directory.
In other words the git status being shown doesn't solely depend on the file you're currently editing, which seems wrong to me.

@maldad If I had to guess your `lineas` directory is probably nested below some other directory/directories you opened with Atom.
If you open the `lineas` directory directly it should work.

**Comment by lee-dohm** [comment] 2016-02-22 22:51
@maldad if what @simonvanderveldt is suggesting is correct, then this is a special case of https://github.com/atom/atom/issues/2203. Can you confirm?

**Comment by maldad** [comment] 2016-02-23 01:18
@simonvanderveldt @lee-dohm 
It's curious, it works only with git directories opened as root directory, thanks for your answers :D

Now I can see my branch, but only if the root directory is a git directory, as you said.

![image](https://cloud.githubusercontent.com/assets/11675538/13238474/d24ef2ec-d998-11e5-997c-4c842392f3d8.png)

**Comment by lee-dohm** [comment] 2016-02-23 02:43
Thanks for following up so quickly, @maldad! I'm going to close this as a duplicate of atom/atom#2203 then. Please subscribe there for updates :grinning:

**Closed by lee-dohm** 2016-02-23 02:43 UTC
Labels: more-information-needed, needs-reproduction

**Comment by ericwmartin** [comment] 2017-08-21 17:26
I'm having a similar issue, but my entire status bar at the bottom is missing. It's not showing branch, language, encoding, or anything. I can't seem to find this setting anywhere. How do I get the status bar back?

[http://imgur.com/a/QhKpG](url)
