### ISSUE TITLE
Uncaught TypeError: Cannot read property 'then' of null

### ISSUE THREAD

**Issue by stefan-kern** [atom/status-bar#154] opened 2016-06-28 07:44 UTC
``/usr/share/atom-beta/resources/app.asar/src/pane.js:1026``

```
TypeError: Cannot read property 'then' of null
    at status-bar-git.GitView.updateAheadBehindCount (/usr/share/atom-beta/resources/app.asar/node_modules/status-bar/lib/git-view.js:229:62)
    at status-bar-git.GitView.update (/usr/share/atom-beta/resources/app.asar/node_modules/status-bar/lib/git-view.js:173:12)
    at /usr/share/atom-beta/resources/app.asar/node_modules/status-bar/lib/git-view.js:80:24
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1135:27)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1105:19)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom-beta/resources/app.asar/src/text-editor.js:740:26)
    at Pane.module.exports.Pane.saveItem (/usr/share/atom-beta/resources/app.asar/src/pane.js:734:18)
    at Pane.saveItem (/usr/share/atom-beta/resources/app.asar/src/pane.js:3:61)
    at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom-beta/resources/app.asar/src/pane.js:717:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom-beta/resources/app.asar/src/workspace.js:690:35)
    at atom-workspace.commandRegistry.add.core:save (/usr/share/atom-beta/resources/app.asar/src/register-default-commands.js:220:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom-beta/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom-beta/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom-beta/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom-beta/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom-beta/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom-beta/resources/app.asar/src/window-event-handler.js:3:61)
```

error triggers on every save
atom version 1.9.0-beta0
status bar 1.3.1

**Comment by lee-dohm** [comment] 2016-07-16 04:55
Please post the full set of diagnostic information that Atom collects. This will help us root cause the problem.

**Comment by stefan-kern** [comment] 2016-07-27 11:11
I discovered this is caused by the atom-hg plugin (i've created an issue there aswell https://github.com/victor-torres/atom-hg/issues/23). I'm not sure if status-bar is at fault here, but heres the diagnostic:

**Atom Version**: 1.9.0-beta1
**System**: Ubuntu 16.04.1
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package, v1.4.0


### Stack Trace

Uncaught TypeError: Cannot read property 'ahead' of null

```
At /usr/share/atom-beta/resources/app.asar/node_modules/status-bar/lib/git-view.js:213

TypeError: Cannot read property 'ahead' of null
    at status-bar-git.GitView.updateAheadBehindCount (/usr/share/atom-beta/resources/app.asar/node_modules/status-bar/lib/git-view.js:213:78)
    at status-bar-git.GitView.update (/usr/share/atom-beta/resources/app.asar/node_modules/status-bar/lib/git-view.js:171:12)
    at status-bar-git.GitView.subscribeToActiveItem (/usr/share/atom-beta/resources/app.asar/node_modules/status-bar/lib/git-view.js:81:19)
    at /usr/share/atom-beta/resources/app.asar/node_modules/status-bar/lib/git-view.js:24:24
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /usr/share/atom-beta/resources/app.asar/src/pane-container.js:346:27
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/usr/share/atom-beta/resources/app.asar/src/pane.js:284:22)
    at Pane.module.exports.Pane.activateItem (/usr/share/atom-beta/resources/app.asar/src/pane.js:433:21)
    at atom-tabs.TabBarView.onMouseDown (/usr/share/atom-beta/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:660:19)
```

### Commands

```
  2x -0:32.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:31.7.0 editor:newline (atom-text-editor.editor.is-focused)
  5x -0:31.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:30.2.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:29.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:26.4.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -0:26.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:24.7.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -0:24.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:22.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:22 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:21.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:20.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:19.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:18.8.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:18.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "activate-power-mode",
      "ctags-status"
    ],
    "ignoredNames": [
      "*.pyc"
    ],
    "openEmptyEditorOnStart": false,
    "projectHome": "~/projects",
    "themes": [
      "atom-material-ui",
      "github-2016-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
aesthetic-ui, v2.0.0 (inactive)
atom-beautify, v0.29.10 (active)
atom-github-2014-syntax, v1.6.0 (inactive)
atom-hg, v2.0.4 (active)
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-dark, v0.2.5 (inactive)
atom-material-syntax-light, v0.4.5 (inactive)
atom-material-ui, v1.3.3 (active)
ava, vundefined (active)
base16-ocean-dark-spacegray, v0.12.0 (inactive)
base16-ocean-dark-syntax-theme, v0.1.9 (inactive)
clipboard-plus, v0.5.1 (active)
color-picker, v2.2.2 (active)
ctags-status, v1.3.5 (inactive)
emmet, v2.4.3 (active)
file-icons, v1.7.17 (active)
git-history, v3.2.0 (inactive)
git-log, v0.4.1 (active)
git-plus, v5.16.2 (inactive)
git-time-machine, v1.5.3 (inactive)
github-2016-syntax, v1.2.0 (active)
indent-guide-improved, v1.4.9 (active)
language-postcss, v1.2.3 (active)
language-restructuredtext, v1.0.0 (active)
linter, v1.11.14 (active)
linter-eslint, v7.2.4 (active)
linter-stylelint, v3.0.2 (active)
minimap, v4.24.7 (active)
minimap-pigments, v0.2.1 (active)
perfectionist, v1.0.1 (inactive)
pigments, v0.31.2 (active)
project-manager, v2.9.7 (active)
pulsing-cursor, v0.3.1 (active)
source-preview, v0.5.0 (inactive)
source-preview-postcss, v0.1.4 (inactive)
spacegray-dark-syntax, v0.2.0 (inactive)
spacegray-dark-ui, v0.12.0 (inactive)
stylefmt, v2.1.0 (inactive)
svg-preview, v0.7.4 (active)
sync-settings, v0.7.2 (active)
terminal-plus, v0.14.5 (active)
toggle-quotes, v1.0.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.0 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by rochford77** [comment] 2016-08-01 19:51
I also had this issue. It also was happening in nuclide (different error, was still complaining about mercurial). 

first of all, I got just reinstalled my os (OS X El Captain) last night and never had this problem before. I downloaded Mercurial from brew, cloned my repos set-up Atom, only to run into this problem. Basically any HG related extension was causing Atom to freak out. Here is how i fixed it:

Uninstalled/Reinstalled Atom (with Atom-HG), didn't fix.

uninstalled Atom, deleted .atom (hidden) folder from home folder, rebooted, reinstalled Atom (and atom-hg), didn't fix.

uninstalled Atom, deleted .atom, uninstalled Mercurial (brew), deleted my repos from my machine, rebooted, installed Mercurial (not using brew), installed Atom (and atom-hg), then pulled my repos in and its all golden. 

hope this helps.

**Comment by GuillaumeAmat** [comment] 2016-08-02 07:44
It seems to be related to the [svn package](https://atom.io/packages/svn). I don't have the issue anymore when it's disabled.

**Comment by rochford77** [comment] 2016-08-03 03:35
See here https://github.com/atom/status-bar/issues/161

**Comment by 50Wliu** [comment] 2016-08-03 13:51
Closing as this issue is caused by the same thing as #161.

**Closed by 50Wliu** 2016-08-03 13:51 UTC
Labels: uncaught-exception
