### ISSUE TITLE
Slow "activation time"

### ISSUE THREAD

**Issue by spencerlyon2** [atom/status-bar#83] opened 2015-06-17 05:16 UTC
time cop consistently reports that this package takes the longest of all my packages to activate (this is a consistent result each time I check time-cop):

![screen shot 2015-06-17 at 1 15 37 am](https://cloud.githubusercontent.com/assets/1001948/8200149/68bd9aa6-148e-11e5-87f0-bfabe35cb252.png)

Any way I can speed this up?

**Comment by stramel** [comment] 2015-06-17 16:27
I am hitting the same issue for Loading and Activation.

**Loading:** 
![screenshot from 2015-06-17 11 19 50](https://cloud.githubusercontent.com/assets/855184/8212741/03e3e9a0-14e3-11e5-87fe-532657c285e1.png)

**Activation:**
![screenshot from 2015-06-17 11 20 05](https://cloud.githubusercontent.com/assets/855184/8212745/081f9474-14e3-11e5-8444-6a699a53a9e7.png)

**PC Specs:**
 - Intel® Core™ i7-4800MQ CPU @ 2.70GHz × 8 
 - 16 GB 1600Mhz
 - Ubuntu 14.04 64-bit
 - 3.13.0-54-generic

**Comment by harrislapiroff** [comment] 2015-06-25 15:17
My machine is admittedly older, but this has consistently been taking more than 1s to activate, which makes Atom very slow to start for me.

2.4 GHz Intel Core 2 Duo
8 GB 1067 MHz DDR3
OS X 10.10.3

**Comment by entr** [comment] 2015-06-25 17:49
![screenshot from 2015-06-25 20 37 48](https://cloud.githubusercontent.com/assets/191571/8361169/21b5f7aa-1b7a-11e5-8d31-d919cd3548aa.png)

Additional packages
```shell
├── autocomplete-paths@1.0.2
├── autocomplete-sass@0.1.0
├── autohide-tree-view@0.20.2
├── docblockr@0.7.2
├── file-icons@1.5.8
├── gist-it@0.7.0
├── git-plus@5.2.1
├── hidpi@0.6.0
├── highlight-selected@0.10.1
├── language-generic-config@0.2.0
├── linter@1.0.4
├── linter-jshint@0.1.6
├── linter-php@0.0.15
├── linter-scss-lint@1.0.4
├── minimap@4.10.0
├── minimap-git-diff@4.1.3
├── minimap-linter@0.1.0
├── project-manager@1.15.10
```

Atom 1.0
Intel® Core™ i7-4712MQ CPU @ 2.30GHz
16 GB 1600Mhz DDR3
Linux Mint 17

**Comment by mnquintana** [comment] 2015-06-25 19:16
Hmm, I wonder if this is because of all the packages consuming the status-bar service...

/cc @jlord

**Comment by prodelay** [comment] 2015-06-29 09:19
For me, `status-bar` is the only one in red zone. :smirk:
![screeny](https://cloud.githubusercontent.com/assets/5169378/8404805/9db78bda-1e58-11e5-97cd-547b9b3a6256.png)

**Comment by lee-dohm** [comment] 2015-07-02 05:03
The easy way to find out if it is because of other packages consuming the `status-bar` service would be if everyone can launch Atom cold by:

1. Completely exiting all instances of Atom
1. Launch Atom using `atom --safe`
1. Report your Timecop results before and after

**Comment by stramel** [comment] 2015-07-02 19:49
@lee-dohm This is "safe" mode opening with a folder of only 4 files.

![screenshot from 2015-07-02 14 45 12](https://cloud.githubusercontent.com/assets/855184/8486247/135c60dc-20c9-11e5-883b-f89fbfe63fd2.png)

However, when I load my normal project folder on open in safe mode and it opens a bunch of files that were opened when it closed. (Using "safe" mode) Every system plugin was in the red on the very first load.

**Comment by kubetz** [comment] 2015-07-02 22:40
@lee-dohm @mnquintana 

I tried to profile status-bar startup in a very primitive way. I set a breakpoint on the 1st line of `status-bar/lib/main.coffee` and then profiled the activation of the status-bar package using Developer Tools. 

What I found out is that `DeprecationCopStatusBarView.updateDeprecatedSelectorCount()` was called **82 times**. After that I disabled `deprecation-cop` package to check the performance differences.

**[Here](https://gist.github.com/kubetz/a9edace33246441e5c68)** is the output of profiling for you too load in Developer Tools.

**Enabled `deprecation-cop`:**
![cop_activated](https://cloud.githubusercontent.com/assets/1128248/8489216/5ca31a7e-2119-11e5-93be-f8820f613072.jpg)

**Disabled `deprecation-cop`:**
![cop_deactivated](https://cloud.githubusercontent.com/assets/1128248/8489219/62a584ac-2119-11e5-8fdb-91b31e26bc09.jpg)

I hope it helps at least a bit! :beers:

**Comment by jerone** [comment] 2015-07-03 07:10
Complete new Windows install today, so complete new install of Atom, running for the second time, resulting in:
![2015-07-03 09_06_20-timecop - c__users_jwm_ atom - atom](https://cloud.githubusercontent.com/assets/55841/8494222/3b6ebb48-2163-11e5-9748-ffad60b0042d.png)

Atom 1.0.0
Windows 8.1 64-bits

**Comment by flashus** [comment] 2016-01-26 05:13
I have problems with status-bar git part. When I open git repository it takes long time to open files there. Atom started from cmd `atom --safe`
![2016-01-26 15-01-42 timecop - c apps idyachenko yandexdisk _src haskell real - atom](https://cloud.githubusercontent.com/assets/415021/12572910/ef09ef9c-c43d-11e5-9738-bb51a0e726b0.png)
Profiling point to  GitRepository.prototype.getDiffStats:
![2016-01-26 15-07-17 real cabal - c apps idyachenko yandexdisk _src haskell real - atom](https://cloud.githubusercontent.com/assets/415021/12572961/914e6c9c-c43e-11e5-8d69-53308d91c386.png)

My system:
Atom 1.3.2,
Windows 7 x64,
git version 1.9.5.msysgit.1

I've tried to speed up git http://stackoverflow.com/questions/4485059/git-bash-is-extremely-slow-in-windows-7-x64
$ git config --global core.preloadindex true
$ git config --global core.fscache true
$ git config --global gc.auto 256
But it doesnt help.

**Comment by lee-dohm** [comment] 2016-01-26 16:19
@flashus I suspect that you have a new underlying issue that we'll need to investigate separately. Would you open a new Issue please?

It also appears that this Issue was fixed by atom/deprecation-cop#56, so I'm going to close this.

**Closed by lee-dohm** 2016-01-26 16:19 UTC
Labels: performance

**Comment by icearith** [comment] 2017-01-23 13:44
![screen shot 2017-01-23 at 13 44 11](https://cloud.githubusercontent.com/assets/2555093/22206174/15c4c826-e172-11e6-99da-2811f44e99c3.png)

I still got this issue

**Comment by lee-dohm** [comment] 2017-01-24 19:23
@icearith Slow activation time is a symptom of an underlying problem. Once we have a better idea of what is causing the problem you're experiencing, then we can open an Issue on the correct repository. For general support questions like this, please post on [Discuss, the official Atom message board](https://discuss.atom.io) and I, or someone else from the community, will help you narrow down the root cause.
