### ISSUE TITLE
Property List files

### ISSUE THREAD

**Issue by sharifzadesina** [atom/status-bar#147] opened 2016-05-07 19:25 UTC
Hi
If we open xml format plist files atom detect that files grammar as binary format plists.
I'm using atom 1.7.3.
Thanks.

![2016-05-07_23-57-06](https://cloud.githubusercontent.com/assets/15300551/15094122/f87cd608-14af-11e6-80f3-86ae54bab82a.png)

I changed grammar manually in bottom image.

![2016-05-07_23-57-41](https://cloud.githubusercontent.com/assets/15300551/15094123/f88103c2-14af-11e6-8955-d939811f4c0e.png)

**Comment by 50Wliu** [comment] 2016-05-07 21:03
This is a duplicate of atom/language-property-list#5 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-05-07 21:03 UTC
