### ISSUE TITLE
Failed to activate the status-bar package

### ISSUE THREAD

**Issue by JeremJR** [atom/status-bar#176] opened 2016-10-27 09:42 UTC
1. Open Atom

![status-bar_failure](https://cloud.githubusercontent.com/assets/1147953/19762434/36579d02-9c3a-11e6-8a78-cf0f8c0504b1.png)

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Ubuntu 14.04.5
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package, v1.4.1

### Stack Trace

Failed to activate the status-bar package

```
At _statusBarItem2.default is not a constructor

TypeError: _statusBarItem2.default is not a constructor
    at Object.consumeStatusBar (/opt/atom/resources/app.asar/node_modules/line-ending-selector/lib/main.js:73:23)
    at Provider.module.exports.Provider.provide (/opt/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:29:52)
    at ServiceHub.module.exports.ServiceHub.provide (/opt/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:30:20)
    at Package.module.exports.Package.activateServices (/opt/atom/resources/app.asar/src/package.js:355:71)
    at Package.module.exports.Package.activateNow (/opt/atom/resources/app.asar/src/package.js:186:16)
    at /opt/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/opt/atom/resources/app.asar/src/package.js:92:15)
    at /opt/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/opt/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/atom/resources/app.asar/src/package-manager.js:538:21)
    at /opt/atom/resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/opt/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/opt/atom/resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/opt/atom/resources/app.asar/src/package-manager.js:497:46)
    at /opt/atom/resources/app.asar/src/atom-environment.js:779:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "telemetryConsent": "no"
  }
}
```

### Installed Packages

```coffee
# User
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.2 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.59.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.68.2 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.209.3 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.33.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.2 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.37.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.42.1 (inactive)
language-html, v0.45.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.23.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.2 (inactive)
language-less, v0.29.5 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.2 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.69.0 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.56.0 (inactive)
language-shellscript, v0.22.4 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.23.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.9 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

seems similar to @a7madgamal comment https://github.com/atom/status-bar/issues/175#issuecomment-254478615

**Comment by Ben3eeE** [comment] 2016-10-27 10:35
This is a duplicate of https://github.com/atom/line-ending-selector/issues/32. Feel free to subscribe there for updates.

**Closed by Ben3eeE** 2016-10-27 10:35 UTC

**Comment by juanfernandoe** [comment] 2017-09-15 21:17
+1

**Comment by RustemB** [comment] 2017-11-11 07:36
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.0-beta0 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package 1.8.14


### Stack Trace

Failed to activate the status-bar package

```
At target[Symbol.iterator] is not a function

TypeError: target[Symbol.iterator] is not a function
    at TooltipManager.add (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/tooltip-manager.js:117:35)
    at StatusBarView.attach (/packages/build/lib/status-bar-view.js:26:34)
    at /packages/build/lib/status-bar-view.js:9:55
    at Config.module.exports.Config.observeKeyPath (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/config.js:674:13)
    at Config.module.exports.Config.observe (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/config.js:155:27)
    at /packages/build/lib/status-bar-view.js:9:17)
    at Object.consumeStatusBar (/packages/build/lib/build.js:331:26)
    at Provider.module.exports.Provider.provide (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.module.exports.Package.activateServices (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package.js:448:77)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package.js:258:22)
    at ~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package.js:227:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package.js:220:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package.js:217:40)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package-manager.js:695:42)
    at packagesToEnable.forEach.name (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package-manager.js:440:51)
    at Array.forEach (native)
    at disabledPackagesSubscription.config.onDidChange (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package-manager.js:440:30)
    at ~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/config.js:693:26
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/config.js:884:35)
    at Config.module.exports.Config.setRawValue (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/config.js:670:25)
    at Config.module.exports.Config.set (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/config.js:248:20)
    at Config.module.exports.Config.removeAtKeyPath (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/config.js:407:18)
    at Package.module.exports.Package.enable (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package.js:84:32)
    at PackageManager.enablePackage (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package-manager.js:246:18)
    at HTMLButtonElement.enablementButtonClickHandler (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/settings-view/lib/package-card.js:361:31)
```

### Commands

```
```

### Non-Core Packages

```
atom-css-comb 3.3.1 
atom-ide-ui 0.5.4 
atom-react-autocomplete 0.1.10 
atom-reactjs-snippets 0.2.1 
atom-typescript 11.0.10 
atom-wallaby 1.0.22 
autocomplete-glsl 0.2.3 
autocomplete-love 0.4.0 
build 0.69.0 
build-sugarss 0.6.2 
busy-signal 1.4.3 
emmet 2.4.3 
Hydrogen 2.0.1 
hyperclick 0.0.0 
hyperclick-love 0.6.0 
ide-html 0.4.1 
ide-json 0.1.0 
ide-python 0.3.0 
ide-vue 0.1.7 
intentions 1.1.5 
language-alda 0.5.0 
language-babel 2.78.0 
language-cython 0.3.0 
language-earl-grey 0.10.0 
language-glsl 2.0.4 
language-kotlin 0.5.0 
language-lolcode 0.2.0 
language-lua 0.9.11 
language-mongodb 0.3.1 
language-pascal 0.20.3 
language-postcss 1.3.1 
language-powershell 4.0.0 
language-renpy 1.6.0 
language-rivescript 1.0.0 
language-rust 0.4.12 
language-scala 1.1.9 
language-vue 0.23.1 
linter 2.2.0 
linter-luaparse 0.2.0 
linter-ui-default 1.6.10 
love-ide 0.17.0 
nebula-syntax 0.4.5 
nebula-ui 0.9.2 
nim 0.3.6 
p5js-snippets 0.3.1 
polymorph 2.2.3 
python-indent 1.1.4 
react-native-components 0.1.1 
script 3.17.3 
select-rectangle 1.0.2 
source-preview-postcss 0.1.4 
tool-bar 1.1.0 
```
