### ISSUE TITLE
Uncaught TypeError: Cannot read property 'ahead' of null

### ISSUE THREAD

**Issue by rochford77** [atom/status-bar#161] opened 2016-08-01 23:21 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.9.0
**System**: Mac OS X 10.11.6
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package, v1.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'ahead' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/status-bar/lib/git-view.js:213

TypeError: Cannot read property 'ahead' of null
    at status-bar-git.GitView.updateAheadBehindCount (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/status-bar/lib/git-view.js:213:78)
    at status-bar-git.GitView.update (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/status-bar/lib/git-view.js:171:12)
    at status-bar-git.GitView.subscribeToActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/status-bar/lib/git-view.js:81:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/status-bar/lib/git-view.js:24:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:346:27
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:284:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:433:21)
    at atom-tabs.TabBarView.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:660:19)
```

### Commands

```
     -2:05.9.0 application:add-project-folder (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-ruby",
      "linter-pylint",
      "linter-javac",
      "linter-htmlhint",
      "linter-csslint"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-hg, v2.0.4 (active)
file-icons, v1.7.17 (active)
linter, v1.11.14 (active)
linter-csslint, v1.3.2 (inactive)
linter-htmlhint, v1.3.0 (inactive)
linter-javac, v1.9.4 (inactive)
linter-jshint, v2.1.0 (active)
linter-pylint, v1.2.1 (inactive)
linter-ruby, v1.2.2 (inactive)
minimap, v4.24.7 (active)
monokai, v0.18.0 (active)
pigments, v0.31.2 (active)
Zen, v0.16.4 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.0 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-08-02 00:37
Hi @rochford77, what were you doing when this occurred?

**Comment by mcihon** [comment] 2016-08-02 00:43
I'm getting the same error.  It occurred after I installed linter-python.  What's happening is the editor appears to be showing the contents of another file, but the settings tab is still selected.  The error re-occurs whenever I switch tabs.

**Comment by rochford77** [comment] 2016-08-02 00:55
nothing, I reset my macbook last night (OS X, made the fun mistake of deleting my boot partition when messing with a trippleboot). this morning I installed a fresh version of OS X Mountain Lion, updated to El Captain, downloaded Atom, downloaded mercurial (from brew), synced my repo, and everything worked great. Then I went through and installed all my old packages and Atom came to a halt. after deleting them one by one, i have come to the realization that it only happens with Mercurial(hg) packages installed. Using the package Atom-hg causes status bar to throw this error. Nuclide throws very similar errors. I tried to uninstall and reinstall atom (while also deleting my .atom folder) reinstalling mercurial from a different source, and resenting my repos. no avail. My windows box does not have this issue, only my mac machine. didn't happen on the same machine yesterday before formatting. Coincidentally i think a new version of atom dropped today, no?

**Comment by rochford77** [comment] 2016-08-02 01:14
Also, it renders atom useless. Cannot open files, save files, switch tabs, open new directories....

**Comment by 50Wliu** [comment] 2016-08-02 01:18
> Coincidentally i think a new version of atom dropped today, no?

Yes, that's correct, Atom 1.9.0.  /cc @maxbrunsfeld, @nathansobo: [this](https://github.com/atom/status-bar/blob/5a41097902c93f267716adbaddd0338bd6b84a59/lib/git-view.coffee#L127) appears to be the relevant line.

**Comment by steffinger** [comment] 2016-08-02 06:49
I'm getting the same error since atom was updated to 1.9.0

It occurs when I try to edit XML files.

Additional information:

It seems to be connected to some languages. I don't get it when editing Javascript files, but I do get it when editing XML files. I didn't try other languages so far. Disabling all packages related to XML does not help. Only disabling the status bar package helped so far.

**Comment by GuillaumeAmat** [comment] 2016-08-02 07:44
It seems to be related to the [svn package](https://atom.io/packages/svn). I don't have the issue anymore when it's disabled.

**Comment by BraveFJ** [comment] 2016-08-02 08:19
I still have this issue under 1.9, without the *svn* package.

**Comment by GuillaumeAmat** [comment] 2016-08-02 08:21
@BraveFJ I'm running the 1.9 too. Maybe your issue is caused by another package?

**Comment by jonasws** [comment] 2016-08-02 08:25
This issue is caused by Atom 1.9 removing `GitRepositoryAsync` as an API, as it was never intended to be public: http://blog.atom.io/2016/08/01/atom-1-9-and-1-10-beta.html. Revert back to Atom 1.8 for the moment to continue using this package.

**Comment by KoningFJ** [comment] 2016-08-02 08:30
Thanks @GuillaumeAmat and @jonasws, I'll go back to 1.8 for now.

**Comment by dropfen** [comment] 2016-08-02 09:39
How do you guys downgrade to 1.8?

**Comment by jonasws** [comment] 2016-08-02 10:34
Either build from source, or download it here: https://github.com/atom/atom/releases/tag/v1.8.0

**Comment by dropfen** [comment] 2016-08-02 13:16
thank you :)


Am 02.08.16 um 12:34 schrieb Jonas Strømsodd:

**Comment by chandramuralis** [comment] 2016-08-02 13:17
Seems like this time Atom Beta 1.10 is more stable than the actual stable release 1.9.0

**Comment by mainstreetmark** [comment] 2016-08-02 13:24
Me too.

**Comment by rochford77** [comment] 2016-08-02 14:19
keep reverting to 1.8 only for it to auto-update back to 1.9. cannot for the life of me find a turn off auto update button.

**Comment by zyy7259** [comment] 2016-08-02 14:54
@rochford77 Go to Atom -> Preferences -> Settings -> Core Settings -> uncheck Automatically update

**Comment by maxbrunsfeld** [comment] 2016-08-02 16:49
Can anyone reproduce this error in Safe mode? As [@jonasws said](https://github.com/atom/status-bar/issues/161#issuecomment-236837592), we're aware that a recent change to Atom broke several packages that were using a private API.

**Comment by rochford77** [comment] 2016-08-02 17:19
@maxbrunsfeld I haven't been running safe mode, however i will tell you that I have NOT been able to reproduce this issue at all today with all my packages disabled/uninstalled (all of my packages have been disabled today....dude's gotta work). my git repos seem to work fine, and my hg repos only have issue with hg dependent packages.

**Comment by maxbrunsfeld** [comment] 2016-08-02 17:31
Thanks for the update @rochford77. I'd like to close this for now, as it was a known result of a change we had to make to fix the crashes mentioned in the blog post. We can reopen this if anyone reproduces this error in Safe mode.

**Closed by maxbrunsfeld** 2016-08-02 17:31 UTC
Labels: bug, uncaught-exception
