### ISSUE TITLE
Only partial file path gets copied from status bar if contains hash key (#)

### ISSUE THREAD

**Issue by pixelchutes** [atom/status-bar#116] opened 2016-01-09 00:18 UTC
When clicking the file path in the status bar to copy it to your clipboard, I noticed that if the path contains a hash key / pound sign (#) that the contents copied to your clipboard are truncated at the hash character.

![filepath](https://cloud.githubusercontent.com/assets/352182/12212791/6be3b744-b62b-11e5-8ea9-163f752b9c8b.jpg)

![filepath](https://cloud.githubusercontent.com/assets/352182/12212781/483f6ab8-b62b-11e5-8eb0-9be7b9eb550e.gif)

## Expected Result:
Clipboard contents:
> /private/tmp/dir.with.#.in.name/subdir/file.txt

## Actual Result:
Clipboard contents:
> /private/tmp/dir.with.

_(Confirmed in `atom-1.3.3` + OS X 10.11.2)_

**Comment by vtambourine** [comment] 2016-10-01 19:56
Is this issue still relevant? I think it can be closed since path merged quite time ago. 
Not reproducing on `atom-1.10.2` + OS X 10.11.6.

**Comment by 50Wliu** [comment] 2016-10-01 20:18
Thanks @vtambourine.

**Closed by 50Wliu** 2016-10-01 20:18 UTC
Labels: bug

**Comment by pixelchutes** [comment] 2016-10-01 20:24
Thank you, have been meaning to close this when I realized recently it was fixed. Appreciate it!
