### ISSUE TITLE
Uncaught Error: Couldn't convert text to a String

### ISSUE THREAD

**Issue by vivekj108** [atom/status-bar#208] opened 2017-08-31 15:18 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.4 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package 1.8.11

### Stack Trace

Uncaught Error: Couldn't convert text to a String

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:536

Error: Couldn't convert text to a String
    at TextBuffer.module.exports.TextBuffer.getTextInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:536:32)
    at Selection.module.exports.Selection.getText (/Applications/Atom.app/Contents/Resources/app/src/selection.js:163:39)
    at TextEditor.module.exports.TextEditor.getSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2212:44)
    at SelectionCountView.module.exports.SelectionCountView.updateCount (/Applications/Atom.app/Contents/Resources/app/node_modules/status-bar/lib/selection-count-view.js:87:70)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/status-bar/lib/selection-count-view.js:78:25
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:187:15)
    at /Applications/Atom.app/Contents/Resources/app/src/view-registry.js:3:65
```

### Commands

```
  4x -4:25.9.0 core:move-down (input.hidden-input)
     -4:18.9.0 core:select-all (input.hidden-input)
  2x -0:39.2.0 core:move-left (input.hidden-input)
  3x -0:39.2.0 core:move-up (input.hidden-input)
     -0:39.1.0 core:move-left (input.hidden-input)
```

### Non-Core Packages

```
markdown-preview-plus 2.4.10 
```

**Comment by rsese** [comment] 2017-08-31 21:57
Thanks for taking the time to contribute!

Though the stack trace isn't exactly the same, I think this may be a duplicate of https://github.com/atom/atom/issues/15325. You may want to subscribe there for updates - if you have steps to reproduce or any other information about the error, feel free to let us know in the issue.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-08-31 21:57 UTC
