### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onDidChangeStatuses' of undefined

### ISSUE THREAD

**Issue by avraamisvi** [atom/status-bar#157] opened 2016-07-16 02:03 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Ubuntu 16.04
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package, v1.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'onDidChangeStatuses' of undefined

```
At /usr/share/atom/resources/app.asar/src/git-repository.js:131

TypeError: Cannot read property 'onDidChangeStatuses' of undefined
    at GitRepository.module.exports.GitRepository.onDidChangeStatuses (/usr/share/atom/resources/app.asar/src/git-repository.js:131:24)
    at status-bar-git.GitView.subscribeToRepositories (/usr/share/atom/resources/app.asar/node_modules/status-bar/lib/git-view.js:106:61)
    at /usr/share/atom/resources/app.asar/node_modules/status-bar/lib/git-view.js:29:24
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.addPath (/usr/share/atom/resources/app.asar/src/project.js:263:29)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/usr/share/atom/resources/app.asar/src/atom-environment.js:1116:26)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:244:18)
    at emitThree (events.js:102:20)
    at EventEmitter.emit (events.js:175:7)
```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by ghermans** [comment] 2016-07-16 04:01
I'm having the same issue as reported above.

## issue report

**Atom Version**: 1.8.0
**System**: Ubuntu 16.04
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package, v1.4.0


### Stack Trace

Uncaught TypeError: Cannot read property 'onDidChangeStatuses' of undefined

```
At /usr/share/atom/resources/app.asar/src/git-repository.js:131

TypeError: Cannot read property 'onDidChangeStatuses' of undefined
    at GitRepository.module.exports.GitRepository.onDidChangeStatuses (/usr/share/atom/resources/app.asar/src/git-repository.js:131:24)
    at status-bar-git.GitView.subscribeToRepositories (/usr/share/atom/resources/app.asar/node_modules/status-bar/lib/git-view.js:106:61)
    at /usr/share/atom/resources/app.asar/node_modules/status-bar/lib/git-view.js:29:24
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.addPath (/usr/share/atom/resources/app.asar/src/project.js:263:29)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:948:41
    at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/application-delegate.js:27:16)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -0:05.9.0 application:add-project-folder (div.package-detail.panels-item)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
autocomplete-html-entities, v0.1.0
php-cs-fixer, v2.5.6

# Dev
No dev packages
```

**Comment by lee-dohm** [comment] 2016-07-16 04:45
Any indication of what you were doing at the time that the error occurred?

**Comment by ghermans** [comment] 2016-07-16 04:49
@lee-dohm i get this error when i try to add a project folder.

**Comment by lee-dohm** [comment] 2016-07-16 04:52
Atom v1.8.0 ships with status-bar v1.2.3. This appears to be a "customized" version of Atom from a Linux package manager that was released without proper testing on their part. Please follow up with the maintainer of that customized version of Atom.

**Comment by 50Wliu** [comment] 2016-07-16 10:01
@ghermans How did you install Atom?

**Comment by SUguy** [comment] 2016-07-16 11:03
I solved this by removing atom (which was downloaded from the official site ) and installing from this
**ppa:webupd8team/atom**
Im running Ubuntu 15.10

**Comment by ghermans** [comment] 2016-07-16 11:58
@50Wliu just from the site and then dpkg -i atom*

**Comment by kn100** [comment] 2016-07-16 13:54
Same issue here on Linux Mint Mate - installed official DEB from Atom.io.

**Comment by avraamisvi** [comment] 2016-07-16 14:42
I have installed Atom from the official site, I opened Atom from console pointing to a folder with a git repository, when I removed the .git folder atom worked normally.

**Comment by dsopscak** [comment] 2016-07-16 16:56
@lee-dohm I'm having the same problem with the official rpm downloaded from https://atom.io/download/rpm and installed on Fedora 23. It does have a newer version of status-bar than 1.2.3. But if that (1.4.0) is an untested custom version, I guess the question is how did it get into that official package.

**Comment by lee-dohm** [comment] 2016-07-16 17:34
@dsopscak That's a good question. I'll look into it.

**Comment by kn100** [comment] 2016-07-16 17:38
@avraamisvi Can also confirm this issue seems to affect git repos

**Comment by artofzen** [comment] 2016-07-16 17:52
Can confirm I am also getting this error on a fresh install of atom 1.8.0 on Ubuntu 16.04 when trying to open a git project folder.

**Comment by lee-dohm** [comment] 2016-07-16 18:02
For all receiving this error message, uninstall the version of Atom you're currently using and install the appropriate one from here:

https://github.com/atom/atom/releases/latest

**Comment by lee-dohm** [comment] 2016-07-16 18:41
Since this is a symptom of a larger Issue, I'm going to close this again. You will want to subscribe to and follow the workaround instructions in https://github.com/atom/atom/issues/12182.

Thanks everyone reporting the problem!

**Closed by lee-dohm** 2016-07-16 18:41 UTC
Labels: linux

**Comment by FaisalFehad** [comment] 2016-07-17 12:24
@SUguy Thank you. Installing it from the repo seems like it has resolved the issue on my Ubuntu MATE 16.04

**Comment by assemusr** [comment] 2016-07-18 13:39
I have installed Atom from the official site on [OS: RHEL 7.2], I tried opening a file in a folder with a git repository, when I chown -R <parent folder> atom worked normally.

**Comment by kunokdev** [comment] 2016-07-18 19:53
Error in Atom lead me here.
I am on fresh Ubuntu 16.06 and I get this error when I try to open a project
`atom projectnme` or even using GUI.

**Comment by Lujaw** [comment] 2016-07-19 03:00
just updated Atom and getting the same error

**Comment by 50Wliu** [comment] 2016-07-19 13:33
Please see @lee-dohm's comment above for how to resolve this issue: https://github.com/atom/status-bar/issues/157#issuecomment-233144775.  Thanks!

**Comment by adi1133** [comment] 2016-07-21 18:30
I am getting this error, I just did a fresh install and have v 1.8.0

At Cannot read property 'onDidChangeStatuses' of undefined.
This only happens when I try to open a folder that is also a git repo. I have git installed (I just cloned).

> TypeError: Cannot read property 'onDidChangeStatuses' of undefined
>     at GitRepository.module.exports.GitRepository.onDidChangeStatuses (/usr/share/atom/resources/app.asar/src/git-repository.js:131:24)
>     at status-bar-git.GitView.subscribeToRepositories (/usr/share/atom/resources/app.asar/node_modules/status-bar/lib/git-view.js:106:61)
>     at status-bar-git.GitView.initialize (/usr/share/atom/resources/app.asar/node_modules/status-bar/lib/git-view.js:32:12)
>     at Object.module.exports.activate (/usr/share/atom/resources/app.asar/node_modules/status-bar/lib/main.js:67:16)
>     at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
>     at /usr/share/atom/resources/app.asar/src/package.js:156:32
>     at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
>     at /usr/share/atom/resources/app.asar/src/package.js:149:26
>     at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
>     at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
>     at /usr/share/atom/resources/app.asar/src/package-manager.js:519:29
>     at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
>     at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:514:19)
>     at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:497:46)
>     at /usr/share/atom/resources/app.asar/src/atom-environment.js:754:28

**Comment by 50Wliu** [comment] 2016-07-21 19:03
Please see @lee-dohm's comment above for how to resolve this issue: #157 (comment). Thanks!

**Comment by adi1133** [comment] 2016-07-21 19:28
Problem solved, I used [this deb package](https://github.com/atom/atom/releases/download/v1.8.0/atom-amd64.deb)

**Comment by hoto** [comment] 2016-07-24 07:28
@adi1133 thanks, installing atom from that deb package also solved my issue

**Comment by flatr0ze** [comment] 2016-07-31 03:05
Able to reproduce if I create a .git repo locally and not pull one from github that I'd create using the web ui.

**Comment by gideondsouza** [comment] 2016-08-05 16:48
This to me seems specific to if I open a file or folder that is a git repo. (Essentially if that file happens to be part of a git repo at any level) I'm on fedora 24 atom 1.8.0
